export let phrases = [
  "Good morning",
  "Good afternoon",
  "Good evening",
  "Good night",
  "Hi",
  "Hello",
  "Hey",
  "How are you?",
  "What's up?",
  "How have you been?",
  "Nice to meet you",
  "My name is [your name]",
  "What's your name?",
  "Please",
  "Thank you",
  "You're welcome",
  "Sorry",
  "Excuse me",
  "No problem",
  "It's okay",
  "Can you help me?",
  "Could you please repeat that?",
  "Where is the bathroom?",
  "Where is the bus stop?",
  "Where is the supermarket?",
  "I don't know",
  "I understand",
  "I don't understand",
  "How much does it cost?",
  "What time is it?",
  "I'm from [country/city]",
  "I like [food/music/sports]",
  "Let's go",
  //introduce yourself
  "How's it going?",
  "Good to see you",
  "Long time no see",
  "It's a pleasure to meet you",
  "I hope you're doing well",
  "Nice to see you",
  "Hope you're having a great day",
  "How's your day going?",
  "Welcome back",
  "Happy Monday",
  "Hope you're feeling better",
  "Hi, I'm [your name]. Nice to meet you",
  "Hey! My name is [your name]. What's yours?",
  "Hi there! I'm [your name]",
  "Hello, my name is [your name]. It's a pleasure to meet you",
  "Good morning/afternoon/evening, I'm [your name]. How do you do?",
  "My name is [your name], and I'm excited to be here today",
  "Hi! I'm [your name]. Looking forward to connecting with you",
  "Hey everyone, I'm [your name]. Excited to be part of this",
  "My name is [your name], and I love discussing about [your interests]",
  //present tense
  "I eat breakfast every morning",
  "You drink coffe at work",
  "He writes emails to his colleagues",
  "She reads a book before bed",
  "We play soccer on weekends",
  "They watch TV in the evening",
  "The dog barks loudly",
  "The sun rises in the east",
  "I walk to school every day",
  "You listen to music on the bus",
  "He cooks dinner for his family",
  "She dances at parties",
  "We study together after class",
  "They travel during summer",
  "The baby cries when hungry",
  "The teacher teaches math",
  "I work in an office",
  "You call your friends often",
  "He drives a car",
  "She swims in the pool",
  "We visit our grandparents monthly",
  "They exercise at the gym",
  "The clock shows the correct time",
  "The train arrives at noon",
  "I laugh at jokes",
  "You help your parents at home",
  "He sings in a band",
  "She paints beautiful pictures",
  "We talk about our dreams",
  "They build houses",
  "The wind blows in the winter",
  "The doctor heals patients",
  "I brush my teeth every morning",
  "You run in the park",
  "He plays the guitar",
  "She wears a dress",
  "We learn new things every day",
  "They shop for groceries",
  "The phone rings often",
  "The flowers bloom in spring",
  "I love spending time with your family",
  "You always tell funny jokes",
  "He enjoys playing video games",
  "She sings in the shower",
  "We walk to the park every afternoon",
  "The cat sleeps on the couch",
  "The rain falls heavily today",
  "I wake up early every morning",
  "You read magazines at lunch",
  "He works at a bank",
  "She talks to her best friend every day",
  "We study English at school",
  "They visit new places on vacation",
  "The baby smiles when happy",
  "The teacher explains the lesson well",
  "I listen to podcasts while working",
  "You drink tea before bed",
  "He washes his car every weekend",
  "She plants flowers in the garden",
  "We celebrate birthdays with cake",
  "They run in the marathon every year",
  "The bus stops at the corner",
  "The clock ticks quietly",
  "I drive to work every morning",
  "You help your sister with homework",
  "He feeds the birds in the park",
  "She buys fresh fruits at the market",
  "We practice yoga in the morning",
  "They cook delicious meals",
  "The dog wags its tail",
  "The sun sets beautifully",
  "I call my mom on Sundays",
  "You wear warm clothes in winter",
  "He eats lunch at noon",
  "She teaches science at school",
  "We play board games on Fridays",
  "They clean the house together",
  "The radio plays good music",
  "The flowers smell amazing",
  //get around town
  "Where is the nearest bus stop?",
  "It's one block away",
  "How do I get to the train station?",
  "Take this street and turn left",
  "Excuse me, can you help me find this address?",
  "Yes, of course! What's the address?",
  "Is there a taxi stand nearby?",
  "Yes, there is one across the street",
  "How much is the fare to downtown?",
  "It's $10 to downtown",
  "Does this bus go to the shopping mall?",
  "No, you need to take a different bus",
  "What time does the next train arrive?",
  "The next train arrives in five minutes",
  "Where can I buy a metro ticket?",
  "You can buy a ticket at the counter",
  "How long does it take to walk to the museum?",
  "It takes about 10 minutes to walk",
  "Is there a bike rental shop around here?",
  "Yes, there is a shop near the square",
  "Which direction should I go for the city center?",
  "Go straight and turn right",
  "Can I pay for the bus with a card?",
  "Yes, you can use a card",
  "How often does the tram run?",
  "Every 15 minutes",
  "Do I need exact change for the bus?",
  "Yes, you need exact change",
  "Where can I catch a taxi?",
  "You can find taxis near the hotel",
  "Is there a public restroom nearby?",
  "Yes, there is one in the mall",
  "How far is the airport from here?",
  "It's about 30 minutes away",
  "What's the best way to get to the stadium?",
  "You should take the subway",
  "Are there any landmarks near this location?",
  "Yes, the museum is near the river",
  "Is this the right platform for the express train?",
  "Yes, this is the right platform",
  "Can you recommend a good restaurant nearby?",
  "There's a great restaurant on this street",
  "Where's the closest ATM?",
  "The ATM is inside the bank",
  "How do I get to the city library?",
  "Go down this road and turn right",
  "Is the park within walking distance?",
  "Yes, it's a short walk",
  "What time do the shops close?",
  "Most shops close at 9 PM",
  "Can you point me in the direction of the hotel?",
  "Yes, it's two blocks that way",
  "Where can I buy a bus pass?",
  "At the station or online",
  "How late do the buses run?",
  "Until midnight",
  "Which subway line goes to the university?",
  "The blue line goes to the university",
  "Does this street lead to the main square?",
  "Yes, keep going straight",
  "Where can I find the pharmacy?",
  "There's a pharmacy at the corner",
  "Can I rent a scooter nearby?",
  "Yes, the shop rents scooters",
  "Is parking available around here?",
  "There's a parking garage nearby",
  "What's the best way to get to the beach?",
  "Take a bus or a taxi",
  "Are there any sightseeing tours?",
  "Yes, city tours are available",
  "Do I need a ticket to enter the park?",
  "No, the park is free to enter",
  "Where is the entrance to the mall?",
  "It's over there, next to the bookstore",
  "How far is the nearest hospital?",
  "About 15 minutes away",
  "Which way should I go for the post office?",
  "Walk straight, then turn left",
  "Where can I buy souvenirs?",
  "There's a souvenir shop in the mall",
  "Is there a pedestrian crossing nearby?",
  "Yes, the crossing is at the traffic light",
  "Can I walk to the theater from here?",
  "Yes, it's a 10-minute walk",
  "Are there bike lanes on this street?",
  "Yes, this street has bike lanes",
  "How much is a one-day metro pass?",
  "It costs $5",
  "Is there a shuttle to the airport?",
  "Yes, the shuttle leaves every hour",
  "Where is the taxi pickup point?",
  "It's at the front of the building",
  "Can I get a city map somewhere?",
  "You can get a map at the tourist center",
  "How do I find my way to the bus terminal?",
  "Walk straight, then turn right",
  "Where is the closest coffee shop?",
  "There's a café on this block",
  "Does the train stop at the museum?",
  "Yes, the train stops at the museum",
  "I need to go to the library to borrow a book",
  "Is there a supermarket close by?",
  "Where can I find a bakery?",
  "Where is the police station?",
  "I need to go to the bank to withdraw money",
  "The bus station is very crowded today",
  "Is the shopping mall open on Sundays?",
  "There is a coffee shop next to the theater",
  "I have an appointment at the dentist's office",
  "Let's go to the park for a walk",
  "Where can I buy fresh fruit?",
  "The church is near the main square",
  "I need to take my car to the gas station",
  "Where is the cinema in this city?",
  "The restaurant serves great seafood",
  "Is there a gym around here?",
  "The school is across from the post office",
  "Is there a pet store in this neighborhood?",
  "Where can I find a florist?",
  "Is there a toy store in this mall?",
  "Is the aquarium open to visitors?",
  "The zoo is located outside the city center",
  "Where is the fire station?",
  "I need to go to the clinic for a check-up",
  "The art gallery has amazing paintings",
  "Is there a music store nearby?",
  "Where can I buy electronics?",
  "The city hall is in the downtown area", /////////////////
  "The embassy is near the government buildings",
  "The butcher shop sells fresh meat",
  "Where is the laundromat?",
  "The car repair shop is on this street",
  "The pet hospital is nearby",
  "Is there a community center in this district?",
  "Clothing store",
  "Furniture store",
  "Nightclub",
  "Playground",
  "Swimming pool",
  "Office Building",
  "Cemetery",
  "Veterinary clinic",
  //refer to family members
  "Mother",
  "Father",
  "Brother",
  "Sister",
  "Grandmother",
  "Grandfather",
  "Uncle",
  "Aunt",
  "Cousin",
  "Nephew",
  "Niece",
  "Stepmother",
  "Stepfather",
  "Stepbrother",
  "Stepsister",
  "Step-grandmother",
  "Step-grandfather",
  "Step-uncle",
  "Step-aunt",
  "Step-cousin",
  "Our mother cooks delicious meals for us every day",
  "Their father teaches them how to ride a bike",
  "His brother plays soccer with his friends after school",
  "Her sister loves reading books before bedtime",
  "Their grandmother tells wonderful stories from her childhood",
  "Our grandfather enjoys gardening on weekends",
  "His uncle takes them to the zoo every summer",
  "Her aunt bakes the best chocolate cake",
  "Their cousin and they go to the same school",
  "His nephew likes playing with toy cars",
  "Her niece enjoys painting colorful pictures",
  "Our stepmother is very kind and caring",
  "Their stepfather helps them with their homework",
  "His stepbrother and he share a room",
  "Her stepsister loves dancing in her free time",
  "Our step-grandmother enjoys knitting warm sweaters",
  "Their step-grandfather tells funny jokes at family gatherings",
  "His step-uncle owns a small bakery in town",
  "Her step-aunt is an excellent piano teacher",
  "Their step-cousin loves playing video games",
  "Our mother and father take us on vacation every year",
  "Their grandparents live in a beautiful house near the beach",
  "Her siblings always support her in everything she does",
  "His uncle and aunt invited them for dinner last night",
  "Their cousins visit them during holidays",
  "Her niece and nephew play together in the park",
  "Our step-family is very friendly and welcoming",
  "Their grandfather and grandmother celebrate their wedding anniversary soon",
  "His brother and sister love listening to music",
  "Her stepbrother and stepsister go to the same school",
];
