export let translatedPhrasesPortuguese = [
  "Bom dia",
  "Boa tarde",
  "Boa noite",
  "Boa noite",
  "Oi",
  "Olá",
  "Ei",
  "Como você está?",
  "E aí?",
  "Como você tem estado?",
  "Prazer em te conhecer",
  "Meu nome é [seu nome]",
  "Qual é o seu nome?",
  "Por favor",
  "Obrigado",
  "De nada",
  "Desculpe",
  "Com licença",
  "Sem problema",
  "Tudo bem",
  "Você pode me ajudar?",
  "Você pode repetir, por favor?",
  "Onde fica o banheiro?",
  "Onde fica o ponto de ônibus?",
  "Onde fica o supermercado?",
  "Eu não sei",
  "Eu entendo",
  "Eu não entendo",
  "Quanto custa?",
  "Que horas são?",
  "Eu sou de [país/cidade]",
  "Eu gosto de [comida/música/esportes]",
  "Vamos",
  // apresente-se
  "Como vai?",
  "Bom te ver",
  "Quanto tempo sem ver você",
  "É um prazer conhecê-lo",
  "Espero que você esteja bem",
  "Prazer em te ver",
  "Espero que você esteja tendo um ótimo dia",
  "Como está sendo o seu dia?",
  "Bem-vindo de volta",
  "Feliz segunda-feira",
  "Espero que você esteja se sentindo melhor",
  "Oi, eu sou [seu nome]. Prazer em te conhecer",
  "Ei! Meu nome é [seu nome]. Qual é o seu?",
  "Oi! Eu sou [seu nome]",
  "Olá, meu nome é [seu nome]. É um prazer conhecê-lo",
  "Bom dia/tarde/noite, eu sou [seu nome]. Como vai?",
  "Meu nome é [seu nome], e estou animado para estar aqui hoje",
  "Oi! Eu sou [seu nome]. Ansioso para me conectar com você",
  "Oi pessoal, eu sou [seu nome]. Estou animado por fazer parte disso",
  "Meu nome é [seu nome], e eu adoro conversar sobre [seus interesses]",
  // tempo presente
  "Eu tomo café da manhã todas as manhãs",
  "Você bebe café no trabalho",
  "Ele escreve e-mails para seus colegas",
  "Ela lê um livro antes de dormir",
  "Nós jogamos futebol nos finais de semana",
  "Eles assistem TV à noite",
  "O cachorro late alto",
  "O sol nasce no leste",
  "Eu caminho para a escola todos os dias",
  "Você escuta música no ônibus",
  "Ele cozinha o jantar para sua família",
  "Ela dança em festas",
  "Nós estudamos juntos depois da aula",
  "Eles viajam durante o verão",
  "O bebê chora quando está com fome",
  "O professor ensina matemática",
  "Eu trabalho em um escritório",
  "Você liga para seus pais com frequência",
  "Ele dirige um carro",
  "Ela nada na piscina",
  "Nós visitamos nossos avós mensalmente",
  "Eles se exercitam na academia",
  "O relógio mostra a hora correta",
  "O trem chega ao meio-dia",
  "Eu rio de piadas",
  "Você ajuda seus pais em casa",
  "Ele canta em uma banda",
  "Ela pinta quadros bonitos",
  "Nós conversamos sobre nossos sonhos",
  "Eles constroem casas",
  "O vento sopra no inverno",
  "O médico cura os pacientes",
  "Eu escovo meus dentes todas as manhãs",
  "Você corre no parque",
  "Ele toca guitarra",
  "Ela usa um vestido",
  "Nós aprendemos coisas novas todos os dias",
  "Eles fazem compras",
  "O telefone toca frequentemente",
  "As flores florescem na primavera",
  "Eu adoro passar tempo com sua família",
  "Você sempre conta piadas engraçadas",
  "Ele gosta de jogar videogames",
  "Ela canta no chuveiro",
  "Nós caminhamos até o parque todas as tardes",
  "O gato dorme no sofá",
  "A chuva cai forte hoje",
  "Eu acordo cedo todas as manhãs",
];
